name: Python package

on: 
  push:
    paths:
    - githubactions_deploy_algorithmia/*
    - .github/workflows/deploy_model.yml

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Deploy model
      env: 
        ALGORITHMIA_API_KEY: YOUR_API_KEY
        ALGORITHMIA_USERNAME: YOUR_USERNAME
      run: |
        python -m pip install --upgrade pip
        pip install algorithmia>=1.2.0 gitpython>=2.1.0 six>=1.12.0
        python githubactions_deploy_algorithmia/model_deploy.py
